services:
  - type: web
    name: roomxqr-frontend
    env: node
    buildCommand: npm ci && npm run build:safe
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://roomapp-backend-1.onrender.com
      - key: NEXT_PUBLIC_BASE_DOMAIN
        value: roomxqr.com
      - key: NEXT_PUBLIC_FRONTEND_URL
        value: roomxqr.com
      - key: HUSKY
        value: 0
