services:
  - type: web
    name: roomxqr-frontend
    env: node
    buildCommand: npm ci && npm run build:safe
    startCommand: npx serve out
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://roomxqr-backend.onrender.com
